import React from 'react';

const TermsOfService: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-8 bg-white">
      <div className="prose prose-lg max-w-none">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        
        <p className="text-gray-600 mb-8">
          Effective Date: {new Date().toLocaleDateString('en-US')}
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Introduction</h2>
          <p className="text-gray-700">
            Welcome to "Text to RedNote". By accessing or using our AI text-to-image service ("Service"), you agree to be bound by these Terms of Service ("Terms"). Please read these Terms carefully before using the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Service Description</h2>
          <p className="text-gray-700 mb-4">
            "Text to RedNote" is an intelligent text-to-image service powered by Doubao AI models. We provide users with:
          </p>
          <ul className="list-disc list-inside text-gray-700 space-y-2">
            <li>Intelligent text splitting and semantic analysis</li>
            <li>AI-based high-quality image generation</li>
            <li>Diverse templates and customization options</li>
            <li>Credit-based payment system</li>
            <li>Batch generation and download functionality</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. User Obligations</h2>
          <p className="text-gray-700 mb-4">By using our Service, you agree to:</p>
          <ul className="list-disc list-inside text-gray-700 space-y-2">
            <li>Provide accurate and complete registration information</li>
            <li>Maintain the security of your account credentials</li>
            <li>Use the Service only for lawful purposes</li>
            <li>Not violate any applicable laws or regulations</li>
            <li>Not attempt to reverse engineer or hack the Service</li>
            <li>Not share account credentials with others</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Intellectual Property Rights</h2>
          <p className="text-gray-700 mb-4">
            <strong>Your Content:</strong> You retain ownership of the text content you input into our Service.
          </p>
          <p className="text-gray-700 mb-4">
            <strong>Generated Images:</strong> You own the images generated by our AI based on your text inputs, subject to these Terms.
          </p>
          <p className="text-gray-700 mb-4">
            <strong>Our Service:</strong> The underlying technology, algorithms, and Service remain our exclusive property.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Privacy and Data Protection</h2>
          <p className="text-gray-700">
            Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the Service, to understand our practices.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Service Availability</h2>
          <p className="text-gray-700 mb-4">
            We strive to maintain high service availability but cannot guarantee uninterrupted access. We may:
          </p>
          <ul className="list-disc list-inside text-gray-700 space-y-2">
            <li>Perform scheduled maintenance</li>
            <li>Update or modify the Service</li>
            <li>Temporarily suspend Service for technical reasons</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Content Guidelines</h2>
          <p className="text-gray-700 mb-4">You may not use our Service to create content that:</p>
          <ul className="list-disc list-inside text-gray-700 space-y-2">
            <li>Violates intellectual property rights</li>
            <li>Contains harmful, offensive, or illegal material</li>
            <li>Promotes violence, hatred, or discrimination</li>
            <li>Infringes on privacy or publicity rights</li>
            <li>Contains false or misleading information</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Payment Terms</h2>
          
          <div className="mb-6">
            <h3 className="text-xl font-semibold text-gray-900 mb-3">8.1 Pricing Plans</h3>
            <ul className="list-disc list-inside text-gray-700 space-y-2">
              <li><strong>Free Trial:</strong> $0 - 100 credits for new users</li>
              <li><strong>Standard Package:</strong> $5 - 550 credits (500 + 50 bonus)</li>
              <li><strong>Unlimited Package:</strong> $599 - Unlimited credits (one-time purchase)</li>
            </ul>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold text-gray-900 mb-3">8.2 Payment Processing</h3>
            <p className="text-gray-700">
              All payments are processed securely through Creem. We do not store your payment information.
            </p>
          </div>

          <div className="mb-6">
            <h3 className="text-xl font-semibold text-gray-900 mb-3">8.3 Refund Policy</h3>
            <p className="text-gray-700">
              Due to the digital nature of our Service, refunds are generally not available once credits are used. However, we may consider refunds on a case-by-case basis for technical issues or billing errors.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Limitation of Liability</h2>
          <p className="text-gray-700 mb-4">
            To the maximum extent permitted by law:
          </p>
          <ul className="list-disc list-inside text-gray-700 space-y-2">
            <li>The Service is provided "as is" without warranties</li>
            <li>We are not liable for indirect, incidental, or consequential damages</li>
            <li>Our total liability is limited to the amount you paid for the Service</li>
            <li>We are not responsible for third-party services or content</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Indemnification</h2>
          <p className="text-gray-700">
            You agree to indemnify and hold us harmless from any claims, damages, or expenses arising from your use of the Service or violation of these Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Termination</h2>
          <p className="text-gray-700 mb-4">
            We may terminate or suspend your account if you:
          </p>
          <ul className="list-disc list-inside text-gray-700 space-y-2">
            <li>Violate these Terms</li>
            <li>Engage in fraudulent activity</li>
            <li>Abuse the Service</li>
          </ul>
          <p className="text-gray-700 mt-4">
            You may terminate your account at any time through your account settings.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">12. Governing Law</h2>
          <p className="text-gray-700">
            These Terms are governed by and construed in accordance with applicable laws. Any disputes will be resolved through binding arbitration.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">13. Changes to Terms</h2>
          <p className="text-gray-700">
            We reserve the right to modify these Terms at any time. We will notify users of significant changes via email or service notifications. Continued use of the Service constitutes acceptance of modified Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">14. Contact Information</h2>
          <p className="text-gray-700">
            If you have questions about these Terms, please contact us:
          </p>
          <div className="mt-4 p-4 bg-gray-50 rounded-lg">
            <p className="text-gray-700">
              <strong>Email:</strong> support@rednotewriter.com<br />
              <strong>Service:</strong> Text to RedNote<br />
              <strong>Subject:</strong> Terms of Service Inquiry
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">15. Severability</h2>
          <p className="text-gray-700">
            If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
          </p>
        </section>

        <div className="mt-12 p-4 bg-blue-50 rounded-lg">
          <p className="text-blue-800 text-sm">
            <strong>Note:</strong> By using Text to RedNote, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service and our Privacy Policy.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;